version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: video-bot-redis
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: video-bot
    depends_on:
      - redis
    env_file:
      - config.env
    volumes:
      - downloads_data:/app/downloads

  worker:
    build: .
    container_name: video-worker
    command: arq core.worker.WorkerSettings
    depends_on:
      - redis
    env_file:
      - config.env
    volumes:
      - downloads_data:/app/downloads

volumes:
  downloads_data:
